id: I7C887CA1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T08:53:44+00:00'
last_modified: '2022-06-07T12:11:54.174778+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22130
  title: གསུང་འབུམ། བཞད་པའི་རྡོ་རྗེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D0F0:
      image_group_id: I5888
      title: ''
      total_pages: 752
      order: 1
      base_file: D0F0.txt
    C999:
      image_group_id: I5889
      title: ''
      total_pages: 588
      order: 2
      base_file: C999.txt
    A4A9:
      image_group_id: I5890
      title: ''
      total_pages: 604
      order: 3
      base_file: A4A9.txt
    '4939':
      image_group_id: I5891
      title: ''
      total_pages: 528
      order: 4
      base_file: 4939.txt
    DAA5:
      image_group_id: I5892
      title: ''
      total_pages: 476
      order: 5
      base_file: DAA5.txt
    22AA:
      image_group_id: I5893
      title: ''
      total_pages: 432
      order: 6
      base_file: 22AA.txt
    377A:
      image_group_id: I5894
      title: ''
      total_pages: 428
      order: 7
      base_file: 377A.txt
    EE83:
      image_group_id: I5895
      title: ''
      total_pages: 556
      order: 8
      base_file: EE83.txt
    DF04:
      image_group_id: I5896
      title: ''
      total_pages: 550
      order: 9
      base_file: DF04.txt
    5F29:
      image_group_id: I5897
      title: ''
      total_pages: 510
      order: 10
      base_file: 5F29.txt
    006D:
      image_group_id: I5898
      title: ''
      total_pages: 506
      order: 11
      base_file: 006D.txt
    8BB8:
      image_group_id: I5899
      title: ''
      total_pages: 624
      order: 12
      base_file: 8BB8.txt
    83D8:
      image_group_id: I5900
      title: ''
      total_pages: 520
      order: 13
      base_file: 83D8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
